### PR TITLE
ADS-1369: Initial tap development

### PR DESCRIPTION
**Pull request by stkbailey**
This tap extracts data from the Udemy For Business API.

### CODE REVIEW

**Comment by stkbailey** [comment]
Issues that I have seen during development:

1. The `courses/list` returns the entire course directory available, and it is very large. There doesn't seem to be a way to onlyl get incremental updates from it either.
2. I don't have the `replication_key` side of things figured out. The `from_date` works for `user_progress` but causes an error in `user-activity`.

**Comment by zane-patten** [comment]
Did we want to have the main stream in its own file (client.py)? Or do we want to group up all of the streams in one file (streams.py)?

**Comment by stkbailey** [comment]
I just followed the cookiecutter format, but do prefer the `streams`-centric approach (sans client). Will update

**Review by zane-patten — APPROVED** [review]
1. The license in the project and the license listed in the pyproject.toml are different.
2. So is the only stream that will update incrementally the user activity one? It's probably fine for now if it's full replication for others, but I wonder why it doesn't work on dates in the courses stream.
3. The client/stream situation is fine as is. If we need to come back and make changes we can always look at it again.

**Comment by zane-patten** [comment]
I approved, but we can talk about the replication key/from date stuff in the morning if you want.

**Pull request merged**
